/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const dsh_atelier_atelier_request_parameter_0$schema = z.string()
const dsh_atelier_atelier_request_result$schema = z.string()

export const TYPERT = {
  package: 'dsh-atelier',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: 'dsh-atelier#atelier/request',
      service: 'atelier',
      namespace: 'atelier',
      method: 'request',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'command',
          wire: 'command',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-atelier#atelier/request:command',
            schema: dsh_atelier_atelier_request_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-atelier#atelier/request:result',
        schema: dsh_atelier_atelier_request_result$schema,
      },
      sourceLocation: {"file":"packages/atelier/src/remote.ts","line":27,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "description": "AtelierRemote 负责跨进程传输，不复制后端的任务执行或重试规则。",
        "summary": "AtelierRemote 负责跨进程传输，不复制后端的任务执行或重试规则。",
        "tags": [],
        "jsDoc": "/** AtelierRemote 负责跨进程传输，不复制后端的任务执行或重试规则。 */",
        "key": "atelier",
        "exportName": "AtelierRemote",
        "members": [
          {
            "kind": "method",
            "name": "request",
            "signature": "@Remote async request(command: string): Promise<string>",
            "summary": "执行页面 JSON 命令，失败通过 Typert Remote 错误返回。",
            "jsDoc": "/**\n * 执行页面 JSON 命令，失败通过 Typert Remote 错误返回。\n * @param command 包含 method、path、body 的 JSON 字符串，或连接配置命令。\n * @returns 不含密钥的业务 JSON。\n */"
          }
        ],
        "types": []
      }
    ],
    "events": [],
    "objects": []
  },
}
