/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const dsh_atelier_atelier_getVersion_result$schema = z.string()

export const TYPERT = {
  package: 'dsh-atelier',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: 'dsh-atelier#atelier/getVersion',
      service: 'atelier',
      namespace: 'atelier',
      method: 'getVersion',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-atelier#atelier/getVersion:result',
        schema: dsh_atelier_atelier_getVersion_result$schema,
      },
      sourceLocation: {"file":"packages/atelier/src/remote.ts","line":15,"column":17},
    },
  ],
  model: {
    "services": [
      {
        "tags": [],
        "key": "atelier",
        "exportName": "AtelierRemote",
        "members": [
          {
            "kind": "method",
            "name": "getVersion",
            "signature": "@Remote async getVersion(): Promise<string>",
            "summary": "返回插件版本，不携带业务配置。",
            "jsDoc": "/** 返回插件版本，不携带业务配置。 */"
          }
        ],
        "types": []
      }
    ],
    "events": [],
    "objects": []
  },
}
