/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$6174656c696572 {
    getVersion: () => Promise<RemoteResult<string>>
  }
  interface TypertRemoteMap {
    'atelier/getVersion': () => Promise<RemoteResult<string>>
  }
  interface TypertRemoteNamespaceMap {
    'atelier': TypertRemoteNamespace$6174656c696572
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
